### ISSUE TITLE
Linux Version: all Sound Devices are listed with only one channel

### ISSUE THREAD

**Issue by LeeO86** [AWAH-SIP/AWAH-SIP_Codec#37]
In GitLab by @andyweiss on Apr 11, 2021, 22:10

Tested with Octo sound card und a USB sound device. Both only show one channel.

Like this the spplittcomb crashes!

**Comment by andyweiss** [comment]
Fixed, but we can only handle symetrical Sound devices. Where the inputcount matches the outputcount.
