### ISSUE TITLE
Linux Version: Sound devices alle auflisten?

### ISSUE THREAD

**Issue by LeeO86** [AWAH-SIP/AWAH-SIP_Codec#40]
In GitLab by @andyweiss on Apr 16, 2021, 12:44

sollen wir alle Varianten auflisten? Sysdefault hw plughw dsnoop etc? Die Namen sind schon sehr kryptisch. Schön wäre hier einwenig aufzuräumen

**Comment by LeeO86** [comment]
In GitLab by @LeeO86 on Apr 26, 2021, 22:49

Ich finde dass wir den User nicht bevormunden sollten.

**Comment by andyweiss** [comment]
machen wir so!
